[package]
name = "mjx-md-voiceover-plugins"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Plugin ecosystem for mjx-md-voiceover."

[dependencies]
mjx-md-voiceover-core = { path = "../mjx-md-voiceover-core" }
mjx-md-voiceover-plugin-latex = { path = "../plugins/mjx-md-voiceover-plugin-latex" }
mjx-md-voiceover-plugin-code = { path = "../plugins/mjx-md-voiceover-plugin-code" }
mjx-md-voiceover-plugin-mermaid = { path = "../plugins/mjx-md-voiceover-plugin-mermaid" }
mjx-md-voiceover-plugin-admonition = { path = "../plugins/mjx-md-voiceover-plugin-admonition" }
mjx-md-voiceover-plugin-table = { path = "../plugins/mjx-md-voiceover-plugin-table" }
serde.workspace = true
